### ISSUE TITLE
Observations

### ISSUE THREAD

**Issue by leealexander** [hivemq/hivemq-mqtt-client-dotnet#72]
I tried using your client and these are the issues I found:
1.  When building your project using Visual Studio 2022 there were 308 warnings (never a good thing to see)
2.  I didn't realise that HiveMQClient Connect returns a status for connection success, I would expect an exception normally. Not realising that I wasn't connected I tried to subscribe to a topic and instead of getting an exception to say I wasn't connected I got a timeout instead.
3. Once I did get the client connected I could publish a topic but not receive even though I subscribed and could see the message in the online client.

**Comment by pglombardo** [comment]
Hi @leealexander!  Some responses, thoughts and questions inline below:

> 1. When building your project using Visual Studio 2022 there were 308 warnings (never a good thing to see)

Yes - definitely not acceptable in the long run.   These will all be resolved before we hit version 1.0.  Right now for Beta, I've focused more on the core functionality/bugs and maturing the API.  There are some decisions to me made with many of those warnings that need to be addressed first.

> 2. I didn't realise that HiveMQClient Connect returns a status for connection success, I would expect an exception normally. Not realising that I wasn't connected I tried to subscribe to a topic and instead of getting an exception to say I wasn't connected I got a timeout instead.

This is a different usage pattern that what I've used in the past.  I'll give this some thought.

> 3. Once I did get the client connected I could publish a topic but not receive even though I subscribed and could see the message in the online client.

This shouldn't be the case but if so, a code example would be very much appreciated to see if I can reproduce the issue.

**Comment by pglombardo** [comment]
Hi @leealexander - the call to `Console.ReadKey()` is blocking the whole program so that background tasks can't run on the event loop.

If you add a ` await Task.Delay(2000).ConfigureAwait(false);` to the top of the `while(true)` block, the message is received and prints the output.

```csharp
while (true)
{
    await Task.Delay(2000).ConfigureAwait(false);
    Console.WriteLine("Press q exit...");
    if (Console.ReadKey().Key == ConsoleKey.Q)
    {
        break;
    }
}
```

<img width="379" alt="Screenshot 2023-06-13 at 15 04 57" src="https://github.com/hivemq/hivemq-mqtt-client-dotnet/assets/395132/632ba0ab-3c1a-46a3-b82b-78bf455f8a00">


One side note, this line was causing an exception for me:

<img width="799" alt="Screenshot 2023-06-13 at 15 00 23" src="https://github.com/hivemq/hivemq-mqtt-client-dotnet/assets/395132/505df1e1-0a5d-45bb-94b7-1899393531e6">

but changing it to an interpolated string fixed it for me:

```csharp
Console.WriteLine($"Message Received: {args.PublishMessage.PayloadAsString}");
```

**Comment by pglombardo** [comment]
Could you try the above changes and let me know?

I'll keep this issue open until I improve some of the feedback/usability and make this stuff a bit more evident for users.

**Comment by pglombardo** [comment]
It's simply because `Console.ReadyKey` is blocking (non asynchronous) so it takes over all execution even when just waiting.  All background async tasks are blocked. 

When you call something with `await`, it gives up execution control to the event scheduler which will execute tasks based on priority and I/O events.

Here is another approach using `Console.KeyAvailable`: https://stackoverflow.com/questions/5891538/listen-for-key-press-in-net-console-app

This isn't anything specific to the HiveMQtt library but instead is just async programming works.

With that said, your line of reasoning isn't out of the ordinary and I don't want other users to hit this issue.  I'll give it some thought but maybe I could create a FAQ or best practices cheat sheet...

**Comment by pglombardo** [comment]
Hi @leealexander - that have been a bunch of improvements over the past 6 months.  Since the items in this issue have been resolved, I'll close out this issue soon.  If anything remains, let me know - I'd be happy to hear/help out.

**Comment by pglombardo** [comment]
Hi @leealexander - hope all is well.  Latest update:

> 1.  When building your project using Visual Studio 2022 there were 308 warnings (never a good thing to see)

We should be at zero now or close to zero.

> 2.  I didn't realise that HiveMQClient Connect returns a status for connection success, I would expect an exception normally. Not realising that I wasn't connected I tried to subscribe to a topic and instead of getting an exception to say I wasn't connected I got a timeout instead.

This was a good point - On failure now, a `HiveMQClientException` is raised now.

> 3. Once I did get the client connected I could publish a topic but not receive even though I subscribed and could see the message in the online client.

I believe this is resolved above.

There have been a [bunch of releases](https://github.com/hivemq/hivemq-mqtt-client-dotnet/releases).  The latest has a big performance improvement as well.

I'll close out this issue but if anything remains, let me know.

**Comment by leealexander** [comment]
Thanks Peter!
