### ISSUE TITLE
Document: How to use Retain flag in Publish

### ISSUE THREAD

**Issue by Spike433** [hivemq/hivemq-mqtt-client-dotnet#97]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/hivemq/hivemq-mqtt-client-dotnet/issues?q=is%3Aissue).
- [x] I've searched the project's [`discussions`](https://github.com/hivemq/hivemq-mqtt-client-dotnet/discussions).

## ❓ Question

I can't find retained flag for `PublishAsync` mehtod?

## 📎 Additional context

There is an [example](https://github.com/dotnet/MQTTnet/wiki/Client#publishing-messages)

**Comment by pglombardo** [comment]
Being in Beta, I'm still working on the interfaces to ease development and make this more evident (including documentation).

Currently, the way to set the `Retain` flag is to construct a `MQTT5PublishMessage` with the `Retain` flag and pass that directly to `PublishAsync`.

```c#
using HiveMQtt.MQTT5.Types;

var message = new MQTT5PublishMessage
{
    Topic = topic,
    Payload = Encoding.ASCII.GetBytes(payload),
    Retain = true,
};

var result = await client.PublishAsync(message).ConfigureAwait(false);
```

I've retargeted this issue so that we document this.  I'll hopefully get to this soon.

**Comment by pglombardo** [comment]
Let's keep this open as a reminder for me to add the documentation.

**Comment by pglombardo** [comment]
[New documentation is live](https://hivemq.github.io/hivemq-mqtt-client-dotnet/docs/how-to/publish) and covers the Retain option in `MQTT5PublishMessage`.

Thanks for pointing this out @Spike433!
